<?php
   /* @var $block Shulgin\Headerstrip\Block\HeaderStrips */
    $msgs = $block->getStrip();
?>
<?php if (count($msgs)):?>
<div class="header-slideshow-container">
    <div class="header-slideshow-inner">

        <?php foreach ($msgs as $msg):?>
            <div class="headerMessagesSlides">
                <div class="msg" ><?= $msg->getMsg()?></div>
                <div class="img"><img src="<?= $msg->getImage()?>" /></div>
            </div>
        <?php endforeach; ?>

        <?php if($block->getShowArrows()) : ?>
            <a class="header-slideshow-prev" onclick="plusSlides(-1)">❮</a>
            <a class="header-slideshow-next" onclick="plusSlides(1)">❯</a>
        <?php endif; ?>

    </div>
</div>
<?php if($block->getShowDots()) : ?>
<div class="dot-container">
    <?php 
    $dotCunter = 1;
    foreach ($msgs as $msg):?>
        <span class="dot" onclick="currentSlide(<?= $dotcunter ?>)"></span>
  <?php $dotcunter++;
    endforeach; ?>
</div>
<?php endif; ?>

<script>

    require([], function() {
    //<![CDATA[
        var slideIndex = 1;
        showSlides(slideIndex);

        setInterval(plusSlides, 10000, 1);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n)
        {
            //debugger;
            var i;
            var slides = document.getElementsByClassName("headerMessagesSlides");
            var dots = document.getElementsByClassName("dot");

            if (n > slides.length) {slideIndex = 1}
            if (n < 1) {slideIndex = slides.length}

            for (i = 0; i < slides.length; i++) {
                //slides[i].style.display = "none";

                slides[i].classList.remove('active');

                // if(slides[i].classList.contains('active')) {
                //     slides[i].classList.replace('active', '');
                // }
            }

            if(dots.length) {
                for (i = 0; i < dots.length; i++) {
                    dots[i].className = dots[i].className.replace(" active", "");
                }
            }

            //slides[slideIndex-1].style.display = "block";
            slides[slideIndex-1].classList.add("active");

            if(dots.length) {
                dots[slideIndex-1].classList.add("active");
            }
            //dots[slideIndex-1].className += " active";
        }
        //]]>
        }
    );

</script>
<?php endif;?>
